
package swing;

import classes.Contact;
import classes.ContactRenderer;
import classes.CustomRenderer;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class ContactBook extends javax.swing.JPanel {

    static String filePath = "src\\contactList.txt";
    
    public ContactBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        EmptyPanel = new javax.swing.JPanel();
        AddContactPersonPanel = new javax.swing.JPanel();
        SurnameText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PhoneNumberText = new javax.swing.JTextField();
        RelationshipText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ListContactsPanel = new javax.swing.JScrollPane();
        PersonToContactList = new javax.swing.JList<>();
        ContactHeadersPanel = new javax.swing.JPanel();
        AddContact = new javax.swing.JLabel();
        ContactList = new javax.swing.JLabel();

        BackgroundPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout EmptyPanelLayout = new javax.swing.GroupLayout(EmptyPanel);
        EmptyPanel.setLayout(EmptyPanelLayout);
        EmptyPanelLayout.setHorizontalGroup(
            EmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        EmptyPanelLayout.setVerticalGroup(
            EmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        BackgroundPanel.add(EmptyPanel, "card4");

        jLabel1.setText("Name");

        jLabel2.setText("Surname");

        jLabel3.setText("Phone Number");

        jLabel4.setText("Relationship");

        SaveButton.setBackground(new java.awt.Color(0, 153, 0));
        SaveButton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(0, 0, 0));
        SaveButton.setText("SAVE");
        SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveButtonMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel5.setText("Add Person To Contact");

        javax.swing.GroupLayout AddContactPersonPanelLayout = new javax.swing.GroupLayout(AddContactPersonPanel);
        AddContactPersonPanel.setLayout(AddContactPersonPanelLayout);
        AddContactPersonPanelLayout.setHorizontalGroup(
            AddContactPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddContactPersonPanelLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(SurnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
            .addGroup(AddContactPersonPanelLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddContactPersonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddContactPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddContactPersonPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddContactPersonPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(362, 362, 362))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddContactPersonPanelLayout.createSequentialGroup()
                        .addGroup(AddContactPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RelationshipText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddContactPersonPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(370, 370, 370))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddContactPersonPanelLayout.createSequentialGroup()
                        .addComponent(SaveButton)
                        .addGap(366, 366, 366))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddContactPersonPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(271, 271, 271))))
        );
        AddContactPersonPanelLayout.setVerticalGroup(
            AddContactPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddContactPersonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(71, 71, 71)
                .addGroup(AddContactPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddContactPersonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SurnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PhoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RelationshipText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(SaveButton)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        BackgroundPanel.add(AddContactPersonPanel, "card3");

        PersonToContactList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", " ", "Item 2", " ", "Item 3", " ", "Item 4", " ", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        PersonToContactList.setAlignmentX(2.0F);
        PersonToContactList.setAlignmentY(1.5F);
        PersonToContactList.setPreferredSize(new java.awt.Dimension(45, 250));
        ListContactsPanel.setViewportView(PersonToContactList);

        BackgroundPanel.add(ListContactsPanel, "card3");

        ContactHeadersPanel.setBackground(new java.awt.Color(153, 153, 153));

        AddContact.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AddContact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        AddContact.setText("Add Contact");
        AddContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddContactMouseClicked(evt);
            }
        });

        ContactList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ContactList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contact-book.png"))); // NOI18N
        ContactList.setText("Contact List");
        ContactList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactListMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ContactHeadersPanelLayout = new javax.swing.GroupLayout(ContactHeadersPanel);
        ContactHeadersPanel.setLayout(ContactHeadersPanelLayout);
        ContactHeadersPanelLayout.setHorizontalGroup(
            ContactHeadersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContactHeadersPanelLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(AddContact)
                .addGap(179, 179, 179)
                .addComponent(ContactList)
                .addContainerGap(217, Short.MAX_VALUE))
        );
        ContactHeadersPanelLayout.setVerticalGroup(
            ContactHeadersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContactHeadersPanelLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(ContactHeadersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddContact)
                    .addComponent(ContactList))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ContactHeadersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContactHeadersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(544, 544, 544))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 100, Short.MAX_VALUE)
                    .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ContactListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactListMouseClicked
        ListContactsPanel.setVisible(true);
        AddContactPersonPanel.setVisible(false);
        EmptyPanel.setVisible(false);
        
        LoadContactList();
       
    }//GEN-LAST:event_ContactListMouseClicked

    private void AddContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddContactMouseClicked
        
        AddContactPersonPanel.setVisible(true);
       ListContactsPanel.setVisible(false);
       EmptyPanel.setVisible(false);
    }//GEN-LAST:event_AddContactMouseClicked

    private void SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseClicked
            
        String name = NameText.getText().trim();
        String surname = SurnameText.getText().trim();
        String phoneNumber = PhoneNumberText.getText().trim();
        String relationship = RelationshipText.getText().trim();
        
        if(name.isEmpty() ||surname.isEmpty() || phoneNumber.isEmpty() ||relationship.isEmpty()){
            JOptionPane.showMessageDialog(null, "Empty field!");
            return;
        }
        
        Contact c = new Contact(name,surname,phoneNumber,relationship);
        saveContact(c);
        
        
        NameText.setText("");
        SurnameText.setText("");
        PhoneNumberText.setText("");
        RelationshipText.setText("");
    }//GEN-LAST:event_SaveButtonMouseClicked

    void saveContact(Contact c){
        File file = new File(filePath);
        try (FileWriter writer = new FileWriter(file,true)) {
            String content = c.getName()+","+c.getSurname()+","+c.getPhoneNumber()+","+c.getRelationship()+"\n";
            writer.write(content);
            System.out.println("Content has been written to the file.");
        } catch (IOException e) {
            System.err.println("An error occurred while writing to the file: " + e.getMessage());
        }
        JOptionPane.showMessageDialog(null, "Contact created");
    }
    

    public ArrayList<Contact> getContactList(){
        ArrayList<Contact> contactList = new ArrayList<>();
        String fileName = "src\\contactList.txt";
        
        try (BufferedReader br = new BufferedReader(new FileReader(fileName))) {
            String line;
            br.readLine();
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                String name = data[0];
                String surname = data[1];
                String phoneNumber = data[2];
                String relationship = data[3];
                Contact contact = new Contact(name,surname,phoneNumber,relationship);
                contactList.add(contact);
                

           }
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        return contactList;
    }
    
    public void LoadContactList()
    {
        DefaultListModel listModel = new DefaultListModel();
        ArrayList<Contact> contactList = getContactList();
       
        
        try{
            
            for(Contact c : contactList){
               listModel.addElement(c.ToString());
            }
                
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Loading error!");
        }
            PersonToContactList.setModel(listModel);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddContact;
    private javax.swing.JPanel AddContactPersonPanel;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JPanel ContactHeadersPanel;
    private javax.swing.JLabel ContactList;
    private javax.swing.JPanel EmptyPanel;
    private javax.swing.JScrollPane ListContactsPanel;
    private javax.swing.JTextField NameText;
    private javax.swing.JList<String> PersonToContactList;
    private javax.swing.JTextField PhoneNumberText;
    private javax.swing.JTextField RelationshipText;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField SurnameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
