/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package swing;

import classes.Flood;
import classes.LandSlide;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gokay
 */
public class FloodAdding extends javax.swing.JInternalFrame {

    /**
     * Creates new form FloodAdding
     */
    public FloodAdding() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        jSeverity = new javax.swing.JTextField();
        s = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLocation = new javax.swing.JTextField();
        l = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        a = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jAdress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jTime = new javax.swing.JTextField();
        t = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jEffectedArea = new javax.swing.JTextField();
        e = new javax.swing.JLabel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(409, 157));

        jPanel15.setMinimumSize(new java.awt.Dimension(200, 42));
        jPanel15.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel15.setLayout(new java.awt.BorderLayout(4, 4));

        jSeverity.setMinimumSize(new java.awt.Dimension(64, 35));
        jSeverity.setPreferredSize(new java.awt.Dimension(64, 27));
        jPanel15.add(jSeverity, java.awt.BorderLayout.CENTER);

        s.setText("Severity");
        s.setMaximumSize(new java.awt.Dimension(50, 16));
        s.setMinimumSize(new java.awt.Dimension(50, 16));
        s.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel15.add(s, java.awt.BorderLayout.PAGE_START);

        jPanel14.setMinimumSize(new java.awt.Dimension(200, 42));
        jPanel14.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel14.setLayout(new java.awt.BorderLayout(4, 4));

        jLocation.setMinimumSize(new java.awt.Dimension(64, 35));
        jLocation.setPreferredSize(new java.awt.Dimension(64, 27));
        jLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLocationemailAdressTextFieldActionPerformed(evt);
            }
        });
        jPanel14.add(jLocation, java.awt.BorderLayout.CENTER);

        l.setText("Location");
        l.setMaximumSize(new java.awt.Dimension(50, 16));
        l.setMinimumSize(new java.awt.Dimension(50, 16));
        l.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel14.add(l, java.awt.BorderLayout.PAGE_START);

        jPanel11.setMinimumSize(new java.awt.Dimension(200, 42));
        jPanel11.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel11.setLayout(new java.awt.BorderLayout(4, 4));

        jTextField6.setMinimumSize(new java.awt.Dimension(64, 35));
        jTextField6.setPreferredSize(new java.awt.Dimension(64, 27));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6emailAdressTextFieldActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField6, java.awt.BorderLayout.CENTER);

        a.setText("Adress");
        a.setMaximumSize(new java.awt.Dimension(50, 16));
        a.setMinimumSize(new java.awt.Dimension(50, 16));
        a.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel11.add(a, java.awt.BorderLayout.PAGE_START);

        jPanel12.setMinimumSize(new java.awt.Dimension(200, 42));
        jPanel12.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel12.setLayout(new java.awt.BorderLayout(4, 4));

        jAdress.setMinimumSize(new java.awt.Dimension(64, 35));
        jAdress.setPreferredSize(new java.awt.Dimension(64, 27));
        jAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdressemailAdressTextFieldActionPerformed(evt);
            }
        });
        jPanel12.add(jAdress, java.awt.BorderLayout.CENTER);

        jLabel3.setText("Adress");
        jLabel3.setMaximumSize(new java.awt.Dimension(50, 16));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 16));
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel12.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel11.add(jPanel12, java.awt.BorderLayout.PAGE_END);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 13)); // NOI18N
        jLabel7.setText("List");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setMinimumSize(new java.awt.Dimension(200, 42));
        jPanel13.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel13.setLayout(new java.awt.BorderLayout(4, 4));

        jTime.setMinimumSize(new java.awt.Dimension(64, 35));
        jTime.setPreferredSize(new java.awt.Dimension(64, 27));
        jPanel13.add(jTime, java.awt.BorderLayout.CENTER);

        t.setText("Time");
        t.setMaximumSize(new java.awt.Dimension(50, 16));
        t.setMinimumSize(new java.awt.Dimension(50, 16));
        t.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel13.add(t, java.awt.BorderLayout.PAGE_START);

        jPanel16.setMinimumSize(new java.awt.Dimension(200, 42));
        jPanel16.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel16.setLayout(new java.awt.BorderLayout(4, 4));

        jEffectedArea.setMinimumSize(new java.awt.Dimension(64, 35));
        jEffectedArea.setPreferredSize(new java.awt.Dimension(64, 27));
        jEffectedArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEffectedAreaemailAdressTextFieldActionPerformed(evt);
            }
        });
        jPanel16.add(jEffectedArea, java.awt.BorderLayout.CENTER);

        e.setText("Effected Area");
        e.setMaximumSize(new java.awt.Dimension(50, 16));
        e.setMinimumSize(new java.awt.Dimension(50, 16));
        e.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel16.add(e, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLocationemailAdressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLocationemailAdressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLocationemailAdressTextFieldActionPerformed

    private void jTextField6emailAdressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6emailAdressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6emailAdressTextFieldActionPerformed

    private void jAdressemailAdressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdressemailAdressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAdressemailAdressTextFieldActionPerformed

    private void jEffectedAreaemailAdressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEffectedAreaemailAdressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEffectedAreaemailAdressTextFieldActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
             // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) FloodTable.jFloodTable.getModel();
        
        String adress = jAdress.getText();
        String severity = jSeverity.getText();
        String location = jLocation.getText();
        String time = jTime.getText();
        String EffectedArea = jEffectedArea.getText();
        String type = "Flood";
       
        if(adress.isEmpty() ||severity.isEmpty() || location.isEmpty() || time.isEmpty()){
            JOptionPane.showMessageDialog(null, "Empty field");
        }
        else{
            
            
           
            
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM/dd/yyyy", Locale.ENGLISH);
            
            try{
                LocalDate date = LocalDate.parse(time, formatter);
                 model.addRow(new Object[]{adress,location,time,type,severity,EffectedArea});
                Flood e = new Flood(adress, Long.valueOf(location), date, type, severity,Integer.parseInt(EffectedArea));
                Ooadproject.incidentList.add(e);
                String filePath = "src\\flood.txt";
                String s = adress + "," + location + "," + time + "," + type + "," + severity + "," + EffectedArea + "\n";
                
                try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath,true))) {
            writer.write(s);
            System.out.println("Successfully written to the file: " + filePath);
                } catch (IOException z) {
            System.err.println("An error occurred while writing to the file: " + z.getMessage());
         }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Date format is not true;");
            }
                
                
                
        
        
        }
        jAdress.setText("");
        jSeverity.setText("");
        jLocation.setText("");
        jTime.setText("");
        jEffectedArea.setText("");
    }//GEN-LAST:event_jPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel e;
    private javax.swing.JTextField jAdress;
    private javax.swing.JTextField jEffectedArea;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jLocation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JTextField jSeverity;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTime;
    private javax.swing.JLabel l;
    private javax.swing.JLabel s;
    private javax.swing.JLabel t;
    // End of variables declaration//GEN-END:variables
}
